- bennu-portal/src/main/webapp/bennu-toolkit/js/bootstrap-wysiwyg.js
This solves an outstanding problem with IE, that prevented the toolbar of working on the html editor.
> Makes HTML Editor work on IE BNN-181 #resolve

- client/bennu-admin/src/main/webapp/bennu-admin/template/CreateUser.html
The photo upload cropper was not working properly due to a missing css file.
> Bug fix: Added link for missing stylesheet. BNN-191 #resolve

- server/bennu-core-test/src/test/java/org/fenixedu/bennu/core/rest/DomainObjectParamConverterTest.java
- server/bennu-core/src/main/java/org/fenixedu/bennu/core/rest/DomainObjectParamConverter.java
> DomainObjectParamConverter now properly sends a 404 error

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/bennu.js
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/datetime.js
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/htmlEditor.js
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/localizedString.js
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/validation.js
> Refactor a bunch of code.

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/datetime.js
This pull has code dependent on the approval of this pull request:
https://github.com/FenixEdu/bennu/pull/191
> Changing the API a bit, the previous one had a typo #resolves BNN-232

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/datetime.js
> Fixes granularity problems and sets unused variables to zero #resolves BNN-194

- bennu-test/src/test/java/org/fenixedu/bennu/core/rest/ThrowableExceptionMapperTest.java
- server/bennu-core/src/main/java/org/fenixedu/bennu/core/rest/ThrowableExceptionMapper.java
* Added test cases
* Made ThrowableExceptionMapper testable
* Issue: BNN-246
> ThrowableException mapper now properly respects WebApplicationException

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/ensure.js
> BNN-234 Last semicolon is necessary due to minification.

- server/bennu-io/src/main/java/org/fenixedu/bennu/io/domain/GenericFile.java
* Also added a method to ensure the slot is properly filled
* Issue: BNN-243
> [io] Defer checksum computation until it is actually needed

- bennu-toolkit/pom.xml
- bennu-toolkit/src/main/webapp/bennu-toolkit/css/toolkit.css
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/mutations.js
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/spinner.js
This pull request adds a variable speed spinner to be used crosswide all our applications
> Adds a standard Spinner for Bennu #resolves BNN-240

- server/bennu-core/src/main/java/org/fenixedu/bennu/core/json/adapters/JarFileViewer.java
- server/bennu-core/src/main/java/org/fenixedu/bennu/core/rest/SystemResource.java
* Also added checksum to each Jar File
* Issue: BNN-248
> [core] Added a public API to expose deployed software

- server/bennu-io/src/main/java/org/fenixedu/bennu/io/domain/FileStorage.java
- server/bennu-io/src/main/java/org/fenixedu/bennu/io/domain/GenericFile.java
- server/bennu-io/src/main/java/org/fenixedu/bennu/io/domain/GroupBasedFile.java
- server/bennu-io/src/main/java/org/fenixedu/bennu/io/domain/LocalFileSystemStorage.java
* This removes the requirement for the whole file to fit in a byte array
* Issue: BNN-244
> [io] Allow creation of GenericFiles based on the File API

- bennu-admin/src/main/webapp/bennu-admin/js/app.js
- bennu-admin/src/main/webapp/bennu-admin/template/portal/configuration.html
- bennu-admin/src/main/webapp/bennu-admin/template/portal/menu.jsp
- bennu-portal/src/main/dml/bennu-portal.dml
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/MenuFunctionality.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/PortalBootstrapper.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/rest/json/MenuItemAdapter.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/rest/json/PortalConfigurationAdapter.java
- Individual url for each menu functionality.
- A {base} placeholder to refer to the main documentation source, used in the instalation
+ This is can be extended to support other placeholders.
- ~~Default values are obtained from the functionality anotations (1).~~
- Adds parsed documentation url to the Menu Functionality API. (2)
- ~~(1) Functionality anotations are implemented in FenixEdu/bennu-spring#6 for spring functionalities and FenixEdu/bennu-renderers#18 for struts functionalites~~
- (2) See FenixEdu/ashes-theme#5 for a possible implementation a the theme.
> Adds a documentation url to functionalities. BNN-175 #resolve

- bennu-portal/src/main/java/org/fenixedu/bennu/portal/rest/PortalConfigurationResource.java
- server/bennu-core/src/main/java/org/fenixedu/bennu/core/filters/StaticCacheFilter.java
- server/bennu-core/src/main/java/org/fenixedu/bennu/core/rest/ProfileResource.java
- server/bennu-core/src/main/java/org/fenixedu/bennu/core/util/CoreConfiguration.java
* Changed the default value to 24h cache
* Issue: BNN-253
> Cache Control header is now configurable

- bennu-core/src/main/java/org/fenixedu/bennu/core/api/GroupResource.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/domain/groups/PersistentDynamicGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/domain/groups/PersistentGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/domain/groups/PersistentUnionGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/domain/groups/PersistentUserGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/AnonymousGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/AnyoneGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/DifferenceGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/DynamicGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/Group.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/IntersectionGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/LoggedGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/NegationGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/NobodyGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/UnionGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/UserGroup.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/domain/groups/UsersCreatedAfterGroup.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestAnonymous.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestAnyone.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestLogged.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestNobody.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestUserGroup.java
> Group.getMembers now returns a stream

- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/api/ExternalApplicationAuthorizationResources.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/api/ExternalApplicationAuthorizationSessionResources.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/api/OAuthAuthorizationProvider.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/api/json/ExternalApplicationAuthorizationSessionAdapter.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/jaxrs/BennuOAuthAuthorizationFilter.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/servlets/OAuthAuthorizationServlet.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/util/OAuthUtils.java
- bennu-test/src/test/java/org/fenixedu/bennu/oauth/OAuthServletTest.java
* Service applications can request an access token on behalf of any
* user.
* In authorizations endpoint filter service applications.
Issue: BNN-259
> Added endpoint to request tokens on user's behalf. BNN-259 #resolve

- bennu-portal/src/main/dml/bennu-portal.dml
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/PortalConfiguration.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalDevModeExceptionHandler.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalExceptionHandler.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalExtension.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalLayoutInjector.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalLoginServlet.java
- default-theme/src/main/webapp/themes/default/default.html
> [portal] Added cache busting mechanisms for theme assets

- bennu-io/src/main/java/org/fenixedu/bennu/io/servlet/FileDownloadServlet.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/util/DownloadUtil.java
> [io] Extracted file download functionality into a utility class

- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalDevModeExceptionHandler.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalExceptionHandler.java
> Guarding request attribute injection to prevent further exception occurences while processing original error/exception.

- bennu-spring/pom.xml
> Upgrade to Spring 4.2.1.RELEASE

- bennu-core/src/main/java/org/fenixedu/bennu/core/api/ProfileResource.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/i18n/I18NFilter.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/security/Authenticate.java
* Removed duplicated REST Endpoint for setting the locale
* Issue: BNN-275
> The user locale is now kept in a cookie

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/userAutocomplete.js
> [toolkit] User Auto Complete now trigger a change event

- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/MenuFunctionality.java
> [portal] If no Base Documentation URL is specified, don't try to replace it

- bennu-portal/src/main/java/org/fenixedu/bennu/alerts/Alert.java
- bennu-portal/src/main/java/org/fenixedu/bennu/alerts/AlertType.java
- bennu-portal/src/main/java/org/fenixedu/bennu/alerts/FlashMap.java
- bennu-portal/src/main/java/org/fenixedu/bennu/alerts/FlashMapManager.java
- bennu-portal/src/main/java/org/fenixedu/bennu/alerts/RedirectAttributes.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalLayoutInjector.java
- bennu-toolkit/pom.xml
- bennu-toolkit/src/main/webapp/bennu-toolkit/css/animate.css
- bennu-toolkit/src/main/webapp/bennu-toolkit/css/toolkit.css
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/alerts.js
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/libs/bootstrap-notify.js
- default-theme/src/main/webapp/themes/default/default.html
May need further enhancements, including moving classes to appropriate packages, but it provides the initial foundations so we can start getting the conversation rolling.
> Alert System and FlashMaps BNN-180 #resolve

- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/FileStorage.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/LocalFileSystemStorage.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/util/DownloadUtil.java
* Moved sendfile code to the Local File System Storage
* Issue: BNN-279
> [io] Added low level API for file download

- bennu-io/src/main/java/org/fenixedu/bennu/io/util/DownloadUtil.java
* Don't assume InputStreams that return less data than
asked are already empty
* Issue: BNN-280
> [io] DownloadUtil can now handle misbehaving InputStreams

- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/DomainStorage.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/FileStorage.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/GenericFile.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/LocalFileSystemStorage.java
> [io] FileStorage now receives a GenericFile

- bennu-portal/src/main/java/org/fenixedu/bennu/alerts/Alert.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalLayoutInjector.java
> [portal] Alerts are now properly flushed within redirects

- default-theme/src/main/webapp/themes/default/default.html
> [default-theme] Ensure alerts are properly escaped

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/alerts.js
> [toolkit] Alerts no longer requires the full toolkit to be loaded

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/browser.js
> Bug Fix: Minified toolkit is now proper Javascript

- bennu-core/pom.xml
- bennu-core/src/main/java/org/fenixedu/bennu/core/domain/Avatar.java
> [core] Removed imgscalr library

- bennu-core/src/main/dml/bennu-core.dml
- bennu-core/src/main/java/org/fenixedu/bennu/core/domain/Bennu.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/domain/BennuTest.java
> [core] Added support for simple properties

- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/CustomGroupRegistry.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/GroupParser.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestExpressionCornerCases.java
> [core] Custom Group arguments are now properly escaped

- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/DifferenceGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/Group.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/IntersectionGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/NegationGroup.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/UnionGroup.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestGroupMath.java
> [core] Composite groups now properly respect precedence rules

- bennu-core/src/main/java/org/fenixedu/bennu/core/domain/exceptions/BennuCoreDomainException.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/CustomGroupRegistry.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/groups/DynamicGroup.java
- bennu-core/src/main/resources/resources/BennuResources_en.properties
- bennu-core/src/main/resources/resources/BennuResources_pt.properties
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestCustomGroup.java
- bennu-test/src/test/java/org/fenixedu/bennu/core/example/groups/TestDynamicGroup.java
> [core] Identifiers are now properly validated

- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/servlets/OAuthAuthorizationServlet.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/LazyForTokenParser.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalExceptionHandler.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalLayoutInjector.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/servlet/PortalLoginServlet.java
- default-theme/src/main/webapp/themes/default/default.html
- pom.xml
* Enabled AutoEscaping for portal themes
* Issue: BNN-297
> Upgrading to Pebble 2.1.0

- bennu-core/src/main/java/org/fenixedu/bennu/core/security/Authenticate.java
- bennu-core/src/main/java/org/fenixedu/bennu/core/security/UserAuthenticationListener.java
> UserAuthenticationListener now receives the Request and Response

- server/bennu-io/src/main/java/org/fenixedu/bennu/io/domain/FileDeleterThread.java
- server/bennu-io/src/main/java/org/fenixedu/bennu/io/servlets/BennuIOContextListener.java
BNN-301 #resolve
BNN-306 #resolve
> File deletion now properly scheduled every 5 mins and at startup. BNN-301 BNN-306 #resolve

- server/bennu-scheduler/src/main/java/org/fenixedu/bennu/scheduler/domain/SchedulerSystem.java
The proposed solution should work, but the safeguard put upon lease renewal depends on an in-memory variable, not entirely transactional. There is a remote chance for failure. A better solution could be made by changing what is stored as lease, maybe including the server id.
> Fix schedulers running on multiple servers. BNN-289 #resolve

- bennu-core/pom.xml
- bennu-core/src/main/webapp/bennu-core/bootstrap.jsp
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/FileStorage.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/GenericFile.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/GroupBasedFile.java
- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/LocalFileSystemStorage.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/domain/ExternalApplication.java
- bennu-oauth/src/main/java/org/fenixedu/bennu/oauth/servlets/OAuthAuthorizationServlet.java
- bennu-oauth/src/main/webapp/bennu-oauth/auth-page.html
- bennu-portal/src/main/webapp/bennu-portal/debugExceptionPage.html
- bennu-portal/src/main/webapp/bennu-portal/login.html
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/group.js
- bennu-toolkit/src/main/webapp/bennu-toolkit/js/validation.js
- default-theme/src/main/webapp/themes/default/css/style.css
- default-theme/src/main/webapp/themes/default/default.html
- pom.xml
This already integrates changes made on the 3.4.x branch
> Fixes on Bennu 4

- bennu-admin/src/main/webapp/bennu-admin/js/app.js
- bennu-admin/src/main/webapp/bennu-admin/template/portal/menu.jsp
- bennu-portal/src/main/dml/bennu-portal.dml
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/api/MenuResource.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/api/json/MenuItemAdapter.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/api/json/SupportConfigurationAdapter.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/api/json/SupportConfigurationViewer.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/MenuItem.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/PortalBootstrapper.java
- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/SupportConfiguration.java
- bennu-portal/src/main/resources/resources/BennuPortalResources.properties
- bennu-portal/src/main/resources/resources/BennuPortalResources_en.properties
- bennu-portal/src/main/resources/resources/BennuPortalResources_pt.properties
Add the ability to have different support emails depending on the part of the application the user is actively on.
> Add contextual form support BNN-311 #resolve

- bennu-admin/src/main/webapp/bennu-admin/js/app.js
- bennu-admin/src/main/webapp/bennu-admin/template/scheduler/log-details.html
- bennu-scheduler/src/main/java/org/fenixedu/bennu/scheduler/api/ExecutionLogResource.java
- bennu-scheduler/src/main/java/org/fenixedu/bennu/scheduler/custom/ClassBean.java
Main changes:
- Added endpoint for task killing
- Updated UI with kill task button
- Now uses getName instead of getSimpleName to avoid killing tasks with same name from different packages.
> Kill running task BNN-344 #resolve

- bennu-toolkit/src/main/webapp/bennu-toolkit/js/localizedString.js
Fixed some type coercion warnings as well.
> Configurable size of LocalizedString textarea and input BNN-350 #resolve

- bennu-portal/src/main/java/org/fenixedu/bennu/portal/domain/MenuItem.java
> Unable to delete functionality that has Support associated BNN-356 #resolve

- bennu-scheduler/src/main/java/org/fenixedu/bennu/scheduler/api/ExecutionLogResource.java
- bennu-scheduler/src/main/java/org/fenixedu/bennu/scheduler/domain/SchedulerSystem.java
- Minor cleanup of "Kill Task" API to improve readability
> View thread stacktrace - support CronTasks BNN-360 #resolve

- bennu-io/src/main/java/org/fenixedu/bennu/io/domain/DriveAPIStorage.java
This reverts commit 1cd51f45a4fb3e1fc4897d1597fe8fb890ea54ea.
> Revert "Use actual inputstream and not a wrapped version BNN-401 #resolve

- bennu-saml-client/src/main/java/org/fenixedu/bennu/saml/client/SAMLClientSDK.java
Signed-off-by: Diogo Silva <diogo.m.r.silva@tecnico.ulisboa.pt>
> Change SAML login Attributes BNN-410 #resolve
